### ISSUE TITLE
nvrtc not found on linux

### ISSUE THREAD

**Issue by nicblanc** [jcuda/jcuda#3]
While generating the makefile with cmake on linux, I have the following error.

> CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
> Please set them or make sure they are set and tested correctly in the CMake files:
> CUDA_nvrtc_LIBRARY
>     linked by target "JNvrtc" in directory /home/nicblanc/JCuda/jcuda/JNvrtcJNI

I link the nvrtc directory manually in the CMakeLists.txt file to bypass this issue.

**Comment by jcuda** [comment]
In which directories are the respective CUDA libraries located on Linux? There should be the `cudart` library and the `nvrtc` library (and others).

This is likely related to the fact that the `FindCUDA.cmake` script does not yet support the nvrtc. That is, it finds all required CUDA libraries (Driver, Runtime, CUBLAS, CUFFT..), but **not** the nvrtc one. It should have been solved with https://github.com/jcuda/jcuda-common/blob/master/JCudaCommon_CMake.txt#L24 :

    # Try to find the NVRTC library in the same directory
    # as the CUDA_CUDA_LIBRARY
    get_filename_component(CUDA_LIBRARY_DIR "${CUDA_CUDA_LIBRARY}" PATH)
    find_library(CUDA_nvrtc_LIBRARY nvrtc ${CUDA_LIBRARY_DIR})

which tries to locate the nvrtc library relative to the main CUDA libraries. On Windows, this causes them to be resolved to 

    CUDA_CUDA_LIBRARY = C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v7.5/lib/x64/cuda.lib
    CUDA_nvrtc_LIBRARY = C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v7.5/lib/x64/nvrtc.lib

Maybe the `find_library` has to be adjusted in some way for Linux...

**Comment by nicblanc** [comment]
This is very odd indeed because the `nvrtc `library is in the same directory as the others: `/usr/local/cuda-7.5/lib64/`

I have no explanation. Do you have access to a linux so that you can try ? Maybe it comes from my installation. I'll try on another computer with ubuntu on monday, I let you know if I still have the problem or not. 

I have another question and I'm not sure where to post it, it concerns concurrent kernel execution with `nvrtc`. When I was using `nvcc`, it was pretty easy to enable per-thread default stream with the `--default-stream per-thread` command line. But this is not available with `nvrtc`, and the other way to activate it is to add `#define the CUDA_API_PER_THREAD_DEFAULT_STREAM` in the C code before including any CUDA headers. 

The only way to do it with JCuda is to add the macro in the JCudaDriver.cpp file before the headers. 
I tried and it worked, but as you can imagine, this is not very convenient. Maybe you can find a way to allow user to activate or not the kernel concurrency.

**Comment by jcuda** [comment]
I don't have a Linux system right here (I should probably set up a virtual box for the compilation tests, at least). 

What does it print when you add

    message(WARNING "The path is ${CUDA_LIBRARY_DIR}")

after https://github.com/jcuda/jcuda-common/blob/master/JCudaCommon_CMake.txt#L26 and run the script? It should at least find the directory ... and to be sure: This is the directory that contains the nvrtc library? (Then it would boil down to why the `find_library` doesn't work...)

I noticed that you set the paths in your branch like this: https://github.com/nicblanc/jcuda/blob/master/JNvrtcJNI/CMakeLists.txt#L25 , and I assume that this works - maybe it can serve as the basis for a workaround if we don't get the `find_library` running correctly...

---

Regarding the `per-thread` flag: You can always ask questions like this one at the [JCuda forum](https://forum.byte-welt.net/byte-welt-projekte-projects/jcuda/?langid=2) (without registration). But (I'm basically the only one who is answering there and) this is very specific and touches technical details that I'm not familiar with. It might be better suited for the NVIDIA forums, as it is more likely to get a profound answer. Right now, I just had a short look at https://devblogs.nvidia.com/parallelforall/gpu-pro-tip-cuda-7-streams-simplify-concurrency/ and think that it *might* be necessary to manually refer to these streams. Particularly, when launching a kernel, it should be possible to pass `JCudaDriver.CU_STREAM_PER_THREAD` as the stream, which *should* expose the desired behavior.

(Actually, I just spent about 2 hours trying to create a sample where one could see the *difference* between both behaviors, but did not succeed. Unfortunately, it's hardly possible to programmatically find out when a kernel execution started...).

**Comment by nicblanc** [comment]
Hi Marco,

Sorry I was a little busy the past few weeks !

I modify the JCudaCommon_CMake.txt and it prints this: 

> The path is /usr/lib/x86_64-linux-gnu

And indeed, the nvrtc library wasn't in this folder.
I don't know how the `FindCUDA.cmake` works, but according the Nvidia documentation, the CUDA toolkit directory on linux should be `/usr/local/cuda-X.Y/`.

It seems that I have a symbolic link to the CUDA library in the `/usr/lib/x86_64-linux-gnu` directory, that makes `FindCUDA.cmake` thinks that the CUDA library is in this directory. And since I have no symbolic link to the nvrtc library here, I only have this issue with nvrtc.

I preferred not to delete this symbolic link, it must have been created for a reason, so I've added a symbolic link to the nvrtc library in the `/usr/lib/x86_64-linux-gnu` folder, and it works.

Maybe you can add a note about this on your web site if some people encounter the same problem.

**Comment by jcuda** [comment]
(Sorry for the delayed response - I'm also not overly relaxed right now)

I also don't know how `FindCUDA` works (it's the largest standard find script, a whopping 72KB - well documented, though, but as long as it "just worked", I hardly saw a reason to dig though this).

I'm not a Linux guy, so could only make un-educated guesses about what's up with these symbolic links. But I'm curious now: What does your CMake say for the value of `CUDA_TOOLKIT_ROOT_DIR`? (I'd guess that it tries to find the libraries *relative* to that one). 

However, if I understood this correctly, then something like

    ln -s /usr/local/cuda-7.5/libnvrtc.so .//usr/lib/x86_64-linux-gnu/libnvrtc.so

**could** solve this issue, right?

**Comment by nicblanc** [comment]
That is exactly what I have done !

I printed `CUDA_TOOLKIT_ROOT_DIR`: ` The toolkit path is /usr/local/cuda`.
so I change `find_library(CUDA_nvrtc_LIBRARY nvrtc ${CUDA_LIBRARY_DIR})` by     `find_library(CUDA_nvrtc_LIBRARY nvrtc ${CUDA_TOOLKIT_ROOT_DIR})` and it worked too.

I think this is better than playing with symbolic link !

**Comment by jcuda** [comment]
Using 

    find_library(CUDA_nvrtc_LIBRARY nvrtc ${CUDA_TOOLKIT_ROOT_DIR})

did not work here on Windows, but I have extended it in a way that will *hopefully* work on both OSes.

**Comment by nicblanc** [comment]
Hi,

Works great on windows.
On linux, after your changes, `cmake `is able to find `nvrtc`, everything compile, but while trying to load the `JNvrtc `library in java, I have now the following problem:

```
java.lang.UnsatisfiedLinkError: Could not load the native library.
Error while loading native library "JNvrtc-linux-x86_64" with base name "JNvrtc"
Operating system name: Linux
Architecture         : amd64
Architecture bit size: 64
Stack trace from the attempt to load the library as a resource:
java.lang.NullPointerException: No resource found with name '/lib/libJNvrtc-linux-x86_64.so'
	at jcuda.LibUtils.loadLibraryResource(LibUtils.java:149)
	at jcuda.LibUtils.loadLibrary(LibUtils.java:83)
	at jcuda.nvrtc.JNvrtc.<clinit>(JNvrtc.java:55)
```

I'm running java with `-Djava.library.path=/home/nicblanc/JCuda/jcuda-main/target/` where all libraries are located (This did not change since the beggining). 

Did you ever encountered this issue ?
Why the `loadLibrary ` is searching in `/lib/` directory ?

`JCudaDriver` library is loaded correctly, maybe something is done for cuda in the `FindCUDA ` but not done for `nvrtc`, some missing link or whatever.

I didn't found any workaround so far ...

**Comment by jcuda** [comment]
Thanks for trying this out. The stack trace is not complete. To elaborate it a bit: 

The "LibUtils" class does **two** attempts to load the library:

 * It first try to load the library as a resource, directly from the JAR file - particularly, from a directory called `/lib` inside the JAR file. This is not "officially" supported right now, but the goal or intention for this was to be able to deploy a *single* JAR file that includes the native libraries.
 * If this fails, it tries to load the library as a file (using the normal `System.loadLibrary` call)

So the stack trace should also contain a part that says

> Stack trace from the attempt to load the library as a file:

and *this* should contain the relevant information here (might it be something like "Can't find dependent libraries", because the NVrtc library is by default not in the LD_LIBRARY_PATH on Linux? But this is just a guess. (The [JCuda FAQ: How to solve an "UnsatisfiedLinkError"](http://forum.byte-welt.net/byte-welt-projekte-projects/swogl-jcuda-jocl/jcuda/2972-jcuda-faq-please-read-posting.html?langid=2) lists other possible reasons). 

But to be sure: When you *manually* bypassed the original issue, it worked for you? (That would be strange...)

**Comment by nicblanc** [comment]
Yes, it was working with my previous version.

But I'm starting to think that my linux environment is completely fucked up, LD_LIBRARY_PATH isn't set ;)
When I set it, it's all good. Don't know why it was working with cuda and not with nvrtc though...

Don't know also why my code was working. Maybe the `link_directories` I had in my code had to do something with it.

**Comment by jcuda** [comment]
I'm not entirely sure about some of the details (e.g. *how* the `LD_LIBRARY_PATH` is set, and/or whether the installation procedure of the CUDA SDK has an influence there). I could only guess right now (maybe the library was originally linked *statically* - but even for that, I'd have to look up whether this is possible for NVRTC at all). 

However, it would be great to figure out the "root cause". If some other linux user could say a word about that, it would at least be an indication of whether your environment is f...ed up, or the current JCuda CMake files...

**Comment by jcuda** [comment]
Note: This was auto-closed by the commit (one has to be careful with the wording in commit messages). If the problem with the UnsatisfiedLinkError still exists, this may be reopened or summarized in a new, dedicated issue.

**Comment by blueberry** [comment]
This still seems to be an issue that requires manual fix: https://github.com/jcuda/jcuda/issues/14

**Comment by jcuda** [comment]
So I'll reopen this one. The issue is not really "urgent", but annoying for the ones who want to build it and manually have to locate the lib in CMake.

The 

    find_library(CUDA_nvrtc_LIBRARY nvrtc ${CUDA_TOOLKIT_ROOT_DIR})

solution thus only seems to be a partial one. Let's see when there is the chance to investigate this further

**Comment by vzamboni** [comment]
I had the same issue and I solved by modifying jcuda/JNvrtcJNI/CMakeLists.txt changing  `${CUDA_nvrtc_LIBRARY}` with absolute path of `libnvrtc.so` (in my case `/usr/local/cuda-9.0/lib64/libnvrtc.so` )

**Comment by jcuda** [comment]
@vzamboni  Do you know which value `CUDA_TOOLKIT_ROOT_DIR` has on your system? With some guesswork, it should be possible to derive how the CMake file has to be modified in order to avoid fixed paths, but still allow it to find the required library on Linux.

**Comment by jcuda** [comment]
This should be resolved according to the PR linked above, so I'll close it for now (until yet another environment causes this issue ;-))
